# Generated by Django 4.2.16 on 2025-04-30 01:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "expenses",
            "0024_remove_recurringincome_owner_delete_recurringexpense_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptupload",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="C:\\Users\\HP\\OneDrive\\Desktop\\fj\\yasir\\media\\receipts"
                ),
                upload_to="receipts/",
            ),
        ),
    ]
